version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"     # Port pour les connexions d'applications (AMQP)
      - "15672:15672"   # Port pour l'interface Web Management
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
